steps:
  # Build the Docker image from the backend directory
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/file-vault-backend', '-f', 'backend/Dockerfile', 'backend']

  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/file-vault-backend']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'file-vault-backend'
      - '--image=gcr.io/$PROJECT_ID/file-vault-backend'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--service-account=file-vault-service-account@file-vault-assessment-484617.iam.gserviceaccount.com'
      - '--add-cloudsql-instances=file-vault-assessment-484617:us-central1:file-vault-db'
      - '--set-env-vars=PROJECT_ID=file-vault-assessment-484617'
      - '--set-env-vars=STAGING_BUCKET=file-vault-assessment-484617-staging'
      - '--set-env-vars=VAULT_BUCKET=file-vault-assessment-484617-vault'
      - '--set-env-vars=DB_SECRET_NAME=db-password'
      - '--set-env-vars=DB_INSTANCE_NAME=file-vault-db'
      - '--set-env-vars=DB_NAME=file_vault'
      - '--set-env-vars=DB_USER=file_vault_user'
      - '--set-env-vars=REGION=us-central1'
      - '--set-env-vars=DOCUMENT_AI_PROCESSOR_ID=4629a5204b746249'
      - '--set-env-vars=DOCUMENT_AI_LOCATION=us'
      - '--set-env-vars=VERTEX_AI_LOCATION=us-central1'
      - '--set-secrets=NEXTAUTH_SECRET=nextauth-secret:latest'
      - '--port=8000'
      - '--memory=1Gi'
      - '--cpu=1'

  # Get the deployed Cloud Run URL
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'get-service-url'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run services describe file-vault-backend \
          --region=us-central1 \
          --format='value(status.url)' > /workspace/service_url.txt
        echo "Cloud Run URL: $$(cat /workspace/service_url.txt)"

  # Update Vercel environment variable with the new URL
  - name: 'gcr.io/cloud-builders/curl'
    id: 'update-vercel-env'
    entrypoint: 'bash'
    secretEnv: ['VERCEL_TOKEN', 'VERCEL_PROJECT_ID']
    args:
      - '-c'
      - |
        SERVICE_URL=$$(cat /workspace/service_url.txt)
        echo "Updating Vercel BACKEND_API_URL to: $$SERVICE_URL"

        # Get existing env var ID (to update instead of create duplicate)
        ENV_ID=$$(curl -s "https://api.vercel.com/v9/projects/$${VERCEL_PROJECT_ID}/env" \
          -H "Authorization: Bearer $${VERCEL_TOKEN}" | \
          jq -r '.envs[] | select(.key=="BACKEND_API_URL") | .id' | head -1)

        if [ -n "$$ENV_ID" ]; then
          # Update existing env var
          curl -X PATCH "https://api.vercel.com/v9/projects/$${VERCEL_PROJECT_ID}/env/$$ENV_ID" \
            -H "Authorization: Bearer $${VERCEL_TOKEN}" \
            -H "Content-Type: application/json" \
            -d "{\"value\":\"$$SERVICE_URL\",\"target\":[\"production\",\"preview\",\"development\"]}"
          echo "✓ Updated existing BACKEND_API_URL in Vercel"
        else
          # Create new env var
          curl -X POST "https://api.vercel.com/v9/projects/$${VERCEL_PROJECT_ID}/env" \
            -H "Authorization: Bearer $${VERCEL_TOKEN}" \
            -H "Content-Type: application/json" \
            -d "{\"key\":\"BACKEND_API_URL\",\"value\":\"$$SERVICE_URL\",\"type\":\"plain\",\"target\":[\"production\",\"preview\",\"development\"]}"
          echo "✓ Created BACKEND_API_URL in Vercel"
        fi

  # Trigger Vercel redeployment to pick up new env var
  - name: 'gcr.io/cloud-builders/curl'
    id: 'redeploy-vercel'
    secretEnv: ['VERCEL_TOKEN', 'VERCEL_PROJECT_ID']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Triggering Vercel redeployment..."
        curl -X POST "https://api.vercel.com/v13/deployments" \
          -H "Authorization: Bearer $${VERCEL_TOKEN}" \
          -H "Content-Type: application/json" \
          -d "{\"name\":\"file-vault\",\"project\":\"$${VERCEL_PROJECT_ID}\",\"target\":\"production\"}"
        echo "✓ Vercel redeployment triggered"

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/vercel-token/versions/latest
      env: 'VERCEL_TOKEN'
    - versionName: projects/$PROJECT_ID/secrets/vercel-project-id/versions/latest
      env: 'VERCEL_PROJECT_ID'

images:
  - 'gcr.io/$PROJECT_ID/file-vault-backend'
